# Generated by Django 4.0.5 on 2022-10-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdone',
            name='orderof_id',
        ),
    ]
