# Generated by Django 4.0.5 on 2022-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymentdone_orderof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdone',
            name='amount_is',
            field=models.FloatField(max_length=200),
        ),
    ]
