# Generated by Django 4.0.5 on 2022-10-06 05:35

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realshop', '0002_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('Mimage', '270x270', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Mimage',
            field=image_cropping.fields.ImageCropField(default=True, upload_to='media/Product_Mimage'),
        ),
    ]
