# Generated by Django 4.0.5 on 2022-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realshop', '0003_products_cropping_alter_products_mimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='available_is',
            new_name='is_offer',
        ),
    ]
