# Generated by Django 4.0.5 on 2022-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realshop', '0004_rename_available_is_products_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
