# Generated by Django 4.0.5 on 2022-10-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realshop', '0005_products_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_offerd',
            field=models.BooleanField(default=False),
        ),
    ]
