# Generated by Django 4.0.5 on 2022-10-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realshop', '0006_category_is_offerd'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_of',
            field=models.IntegerField(default=0),
        ),
    ]
