# Generated by Django 4.0.5 on 2022-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=20)),
                ('offer', models.TextField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
