# Generated by Django 4.0.5 on 2022-09-19 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupoun',
            name='date_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
