# Generated by Django 4.0.5 on 2022-10-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_coupounvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupounvalid',
            name='order_id',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
