# Generated by Django 4.0.5 on 2022-09-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordered_addreseof_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
