# Generated by Django 4.0.5 on 2022-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordered_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='PaymentMode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
