# Generated by Django 4.0.5 on 2022-10-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordered_paymentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='is_shiped',
            field=models.BooleanField(default=True),
        ),
    ]
