# Generated by Django 4.0.5 on 2022-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordered_is_shiped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order conformed', 'Order Confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned'), ('return_accepted', 'return_accepted')], default='Order Confirmed', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='status',
            field=models.CharField(choices=[('Order Conformed', 'Order Confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned'), ('return_accepted', 'return_accepted')], default='Order Confirmed', max_length=100),
        ),
    ]
