# Generated by Django 4.0.5 on 2022-10-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymentdone_orderof_id'),
        ('orders', '0007_alter_order_status_alter_ordered_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentdone'),
            preserve_default=False,
        ),
    ]
